language: python
dist: xenial
sudo: true
python:
  - 3.6
  - 3.7
  - nightly

matrix:
  allow_failures:
  - python: nightly

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python i18n.py check test/datasets --exts csv,xml,xlsx
  - python i18n.py export -c test/config.yml
  - python i18n.py import -c test/config.yml
