# YAML

langs:
  - zh_TW
  - en_US

# 语言包目录
langsdir: languages

# 语言包类型
# po    导出为.po文件
# excel 导出为.xlsx文件
translation: excel

# 输出目录
outputdir: output


# 表数据
sheets:
  csv:
    extension: csv
    tawords: [words, 英雄]
  xml:
    extension: xml
    static_unlock: [des, wave_name, content]

