# YAML

langs:
  - zh_TW
  - en_US

# 语言包目录
langsdir: languages

# 输出目录
outputdir: output


# 表数据
sheets:
  csv:
    extension: csv
    tawords: [words, 英雄]
  xml:
    extension: xml
    static_unlock: [des, wave_name, content]

